-- THOSP_ESPECIALIDADES
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE THOSP_ESPECIALIDADES';
END;
/

-- THOSP_CLIENTES
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE THOSP_CLIENTES';
END;
/

-- THOSP_MEDICOS
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE THOSP_MEDICOS';
END;
/

-- THOSP_CITAS
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE THOSP_CITAS';
END;
/

-- THOSP_DIAGNOSTICO
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE THOSP_DIAGNOSTICO';
END;
/