SET SERVEROUTPUT ON;

-- THOSP_ESPECIALIDADES
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE THOSP_ESPECIALIDADES (
        TN_IdEspecialidad NUMBER PRIMARY KEY NOT NULL,
        TC_DscEspecialidad VARCHAR2(100) NOT NULL
    )';
END;
/
 
-- THOSP_CLIENTES
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE THOSP_CLIENTES (
        TN_IdCliente NUMBER PRIMARY KEY NOT NULL,
        TC_Nombre VARCHAR2(60) NOT NULL,
        TC_Ap1 VARCHAR2(60) NOT NULL,
        TC_Ap2 VARCHAR2(60) NOT NULL,
        TC_NumTelefono VARCHAR2(15) NOT NULL,
        TC_CorreoElectronico VARCHAR2(100) NOT NULL
    )';
END;
/
 
-- THOSP_MEDICOS
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE THOSP_MEDICOS (
        TN_IdMedico NUMBER PRIMARY KEY NOT NULL,
        TC_NombreMedico VARCHAR2(100) NOT NULL,
        TN_IdEspecialidad NUMBER NOT NULL,
        CONSTRAINT FK_TN_IdEspecialidad_Medico FOREIGN KEY (TN_IdEspecialidad) 
        REFERENCES THOSP_ESPECIALIDADES(TN_IdEspecialidad) ON DELETE CASCADE
    )';
END;
/
 
-- THOSP_CITAS
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE THOSP_CITAS (
        TN_IdCita NUMBER PRIMARY KEY NOT NULL,
        TN_IdCliente NUMBER REFERENCES THOSP_CLIENTES(TN_IdCliente) ON DELETE CASCADE,
        TN_IdMedico NUMBER REFERENCES THOSP_MEDICOS(TN_IdMedico) ON DELETE CASCADE,
        TN_IdEspecialidad NUMBER REFERENCES THOSP_ESPECIALIDADES(TN_IdEspecialidad) ON DELETE CASCADE,
        TF_FecCita TIMESTAMP NOT NULL
    )';
END;
/
 
-- THOSP_DIAGNOSTICO
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE THOSP_DIAGNOSTICO (
        TN_IdDiagnostico NUMBER PRIMARY KEY NOT NULL,
        TN_IdCita NUMBER NOT NULL,
        TC_DscDiagnostico VARCHAR2(500) NOT NULL,
        CONSTRAINT FK_TN_IdCita_Diagnostico FOREIGN KEY (TN_IdCita) 
        REFERENCES THOSP_CITAS(TN_IdCita) ON DELETE CASCADE
    )';
END;
/